### ISSUE TITLE
Error ./install-script.sh installing npm

### ISSUE THREAD

**Issue by Seikon** [bennetthardwick/darknet.js#14]
Hello,
On Windows 10 I´m getting this error on npm install:

./install-script.sh
The command "." is either misspelled or could not be found.

I think the problem is with the first "." in the comand. Does anyone know how to avoid or solve that?

thank you

**Comment by bennetthardwick** [comment]
Hi! Unfortunately you won't be able to install darknet.js on Windows like you would a normal npm package. I have successfully installed it on Windows using the Linux Sub-system. You can read more about installing it [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by LorisLombardo87** [comment]
Hi @bennetthardwick, i'm successfully running darknet on windows using this repo https://github.com/AlexeyAB/darknet and now i want to access it from node using your code...

apart form making darknet what is the install-script doing?
what can i do in my windows env. to run your code?

Thanks, Loris

**Comment by bennetthardwick** [comment]
Hey @LorisLombardo87, currently the install script pulls the darknet repo and builds it. Before building it edits the makefile so that users can enable GPU support, etc., depending on environment variables that have been exported.

In order to get it working on Windows, you'd need to update the install script / create a new one that will pull from AlexeyAB's fork and build it. Then update the `binding.gyp` file so that it points to the `libdarknet` file (probably a `dll`).

I've want to try and support Windows, so created #25 to track the progress. I'll probably have some time this weekend to give it a go.

**Comment by haviduck** [comment]
the vcpkg approach should work.. ima see how it turns out.
