### ISSUE TITLE
Use AlexeyAB fork

### ISSUE THREAD

**Issue by dreambit** [bennetthardwick/darknet.js#30]
@bennetthardwick Hi

Do u have plans to use [AlexeyAB fork](https://github.com/AlexeyAB/darknet)? 

Thanks

**Comment by bennetthardwick** [comment]
Hey @dreambit, I don't have any plans to change over to the AlexyAB fork just because I haven't really tested it. If it's so you can use darknet.js on Windows, I added #25 to track this.

If it's just for extra performance on the currently supported platforms - it shouldn't be too hard to add some extra logic if when installing the package to make it use that fork (provided the API is compatible).

**Comment by xellDart** [comment]
Hi, this supports yolo v4 tiny models?

**Comment by bennetthardwick** [comment]
Hey @xellDart I've just updated to the AlexyAB fork, so v4 should work :+1: If you run into any issues please let me know
